In [1]:
import pandas

In [2]:
food_info = pandas.read_csv('csv/food_info.csv')
print(type(food_info))

<class 'pandas.core.frame.DataFrame'>

In [3]:
column_names = food_info.columns
print(column_names)
print(food_info.head(3))
dimensions = food_info.shape
print("dimension: {}".format(dimensions))
num_rows = dimensions[0]
print("rows: {}".format(num_rows))
num_cols = dimensions[1]
print("columns: {}".format(num_cols))

Index(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg',
       'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)',
       'Cholestrl_(mg)'],
      dtype='object')
   NDB_No                 Shrt_Desc  Water_(g)  Energ_Kcal  Protein_(g)  \
0    1001          BUTTER WITH SALT      15.87         717         0.85
1    1002  BUTTER WHIPPED WITH SALT      15.87         717         0.85
2    1003      BUTTER OIL ANHYDROUS       0.24         876         0.28

   Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  Fiber_TD_(g)  Sugar_Tot_(g)  \
0          81.11     2.11            0.06           0.0           0.06
1          81.11     2.11            0.06           0.0           0.06
2          99.48     0.00            0.00           0.0           0.00

        ...        Vit_A_IU  Vit_A_RAE  Vit_E_(mg)  Vit_D_mcg  Vit_D_IU  \
0       ...          2499.0      684.0        2.32        1.5      60.0
1       ...          2499.0      684.0        2.32        1.5      60.0
2       ...          3069.0      840.0        2.80        1.8      73.0

   Vit_K_(mcg)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)  Cholestrl_(mg)
0          7.0      51.368       21.021        3.043           215.0
1          7.0      50.489       23.426        3.012           219.0
2          8.6      61.924       28.732        3.694           256.0

[3 rows x 36 columns]
dimension: (8618, 36)
rows: 8618
columns: 36

In [4]:
# Series object representing the row at index 0.
row = food_info.loc[0]
print(type(row))
row.head()

<class 'pandas.core.series.Series'>

NDB_No                     1001
Shrt_Desc      BUTTER WITH SALT
Water_(g)                 15.87
Energ_Kcal                  717
Protein_(g)                0.85
Name: 0, dtype: object

In [5]:
# DataFrame containing the rows at index 3, 4, 5, and 6 returned.
food_info.loc[3:6]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0
6,1007,CHEESE CAMEMBERT,51.80,300,19.80,24.26,3.68,0.46,0.0,0.46,...,820.0,241.0,0.21,0.4,18.0,2.0,15.259,7.023,0.724,72.0

In [6]:
# DataFrame containing the rows at index 2, 5, and 10 returned. Either of the following work.
# Method 1
two_five_ten = [2,5,10] 
food_info.loc[two_five_ten]

# Method 2
food_info.loc[[2,5,10]]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0
10,1011,CHEESE COLBY,38.20,394,23.76,32.11,3.36,2.57,0.0,0.52,...,994.0,264.0,0.28,0.6,24.0,2.7,20.218,9.280,0.953,95.0

In [7]:
# Series object representing the "NDB_No" column.
ndb_col = food_info["NDB_No"]

columns = ["Zinc_(mg)", "Copper_(mg)"]
zinc_copper = food_info[columns]

In [8]:
div_1000 = food_info["Iron_(mg)"] / 1000
div_1000.head()

0    0.00002
1    0.00016
2    0.00000
3    0.00031
4    0.00043
Name: Iron_(mg), dtype: float64

In [9]:
water_energy = food_info["Water_(g)"] * food_info["Energ_Kcal"]
water_energy.head()

0    11378.79
1    11378.79
2      210.24
3    14970.73
4    15251.81
dtype: float64

In [10]:
# The largest value in the "Energ_Kcal" column.
max_calories = food_info["Energ_Kcal"].max()
max_calories

902

In [11]:
# Add new column to dataframe
iron_grams = food_info["Iron_(mg)"] / 1000  
food_info["Iron_(g)"] = iron_grams

In [12]:
# Sorts the DataFrame in-place, rather than returning a new DataFrame.
food_info.sort_values("Sodium_(mg)", inplace=True)

# Sorts by descending order, rather than ascending.
food_info.sort_values("Sodium_(mg)", inplace=True, ascending=False)

food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g)
276,2047,SALT TABLE,0.20,0,0.00,0.00,99.8,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.00033
5814,18372,LEAVENING AGENTS BAKING SODA,0.20,0,0.00,0.00,36.9,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.00000
6192,19225,DESSERTS RENNIN TABLETS UNSWTND,6.50,84,1.00,0.10,72.5,19.8,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,0.041,0.038,0.007,0.0,0.00707
1242,6075,SOUP BF BROTH OR BOUILLON PDR DRY,3.27,213,15.97,8.89,54.5,17.4,0.0,16.71,...,0.0,2.17,0.0,0.0,3.2,4.320,3.616,0.332,10.0,0.00100
1245,6081,SOUP CHICK BROTH CUBES DRY,2.50,198,14.60,4.70,54.7,23.5,0.0,0.00,...,0.0,0.09,NaN,NaN,0.0,1.200,1.920,1.620,13.0,0.00187

## dataframe.loc() Vs dataframe.iloc()

`loc` uses "lable" while `iloc` uses "integer"

In [13]:
food_info.loc[0]

NDB_No                         1001
Shrt_Desc          BUTTER WITH SALT
Water_(g)                     15.87
Energ_Kcal                      717
Protein_(g)                    0.85
Lipid_Tot_(g)                 81.11
Ash_(g)                        2.11
Carbohydrt_(g)                 0.06
Fiber_TD_(g)                      0
Sugar_Tot_(g)                  0.06
Calcium_(mg)                     24
Iron_(mg)                      0.02
Magnesium_(mg)                    2
Phosphorus_(mg)                  24
Potassium_(mg)                   24
Sodium_(mg)                     643
Zinc_(mg)                      0.09
Copper_(mg)                       0
Manganese_(mg)                    0
Selenium_(mcg)                    1
Vit_C_(mg)                        0
Thiamin_(mg)                  0.005
Riboflavin_(mg)               0.034
Niacin_(mg)                   0.042
Vit_B6_(mg)                   0.003
Vit_B12_(mcg)                  0.17
Vit_A_IU                       2499
Vit_A_RAE                       684
Vit_E_(mg)                     2.32
Vit_D_mcg                       1.5
Vit_D_IU                         60
Vit_K_(mcg)                       7
FA_Sat_(g)                   51.368
FA_Mono_(g)                  21.021
FA_Poly_(g)                   3.043
Cholestrl_(mg)                  215
Iron_(g)                      2e-05
Name: 0, dtype: object

In [14]:
food_info.iloc[0]

NDB_No                   2047
Shrt_Desc          SALT TABLE
Water_(g)                 0.2
Energ_Kcal                  0
Protein_(g)                 0
Lipid_Tot_(g)               0
Ash_(g)                  99.8
Carbohydrt_(g)              0
Fiber_TD_(g)                0
Sugar_Tot_(g)               0
Calcium_(mg)               24
Iron_(mg)                0.33
Magnesium_(mg)              1
Phosphorus_(mg)             0
Potassium_(mg)              8
Sodium_(mg)             38758
Zinc_(mg)                 0.1
Copper_(mg)              0.03
Manganese_(mg)            0.1
Selenium_(mcg)            0.1
Vit_C_(mg)                  0
Thiamin_(mg)                0
Riboflavin_(mg)             0
Niacin_(mg)                 0
Vit_B6_(mg)                 0
Vit_B12_(mcg)               0
Vit_A_IU                    0
Vit_A_RAE                   0
Vit_E_(mg)                  0
Vit_D_mcg                   0
Vit_D_IU                    0
Vit_K_(mcg)                 0
FA_Sat_(g)                  0
FA_Mono_(g)                 0
FA_Poly_(g)                 0
Cholestrl_(mg)              0
Iron_(g)              0.00033
Name: 276, dtype: object